### ISSUE TITLE
Why is Caret opening .zip files

### ISSUE THREAD

**Issue by cottonwool** [thomaswilburn/Caret#493] opened 2016-02-13 00:27 UTC
When I opened a .zip file today it was opened in Caret instead of being mounted. If I right-mouse (two finger tap) on the .zip I get the option to Open with... where Caret is the default and Zip unpacker is the second choice.

How do I stop Caret opening .zip files?

I'm running Caret 1.6.7 and Chromeos Version 48.0.2564.109 (64-bit) stable channel.

**Comment by thomaswilburn** [comment] 2016-02-13 00:29
We registered for all file permissions as a part of the changes explained in #492. So yes, we basically listen for everything now. I'd be happy to take suggestions on how to make the filter more fine-grained without excluding typical script files that Chrome OS doesn't necessarily know about out of the box.

**Comment by cottonwool** [comment] 2016-02-13 01:19
I think the land grab in #492 was a step too far when it makes Caret the default application for opening files by default.

I can understand a Caret user wanting to be able to open files with arbitrary extensions but it should be the user who chooses defaults for a utility like this.

You have broken how Zip files are mounted!
Mounting Zip files is part of the general operating system behaviour (file management) and should not be usurped by a mere application.

**Comment by thomaswilburn** [comment] 2016-02-13 01:34
I understand your frustration, and largely agree. The question is, is there a good way to exempt .zip files from the manifest without sacrificing the wildcards that we need for general-purpose editing? I will investigate, but I don't have a timeframe--suggestions or pull requests would be welcome if you want to help with this.

**Comment by thomaswilburn** [comment] 2016-02-13 04:16
I'm re-closing this, because on reflection it's not a Caret bug. The issue is with the Files app, which should not have unregistered the default file handler for .zip just because we registered for a wider MIME type. I would recommend filing a bug on crbug.com, and seeing if they can pick it up. I will look at ways to narrow the breadth of Caret's file registration, but I'm reluctant to risk excluding valid file types without a lot more information on how it will behave (and this manifest feature is woefully under-documented, which means I will have to do a lot of experimentation).

In the meantime, please remember that you can re-set the default for files by using the "Open with" menu in the Files toolbar.

**Closed by thomaswilburn** 2016-02-13 04:16 UTC

**Comment by cottonwool** [comment] 2016-02-13 14:04
https://code.google.com/p/chromium/issues/detail?id=586742
Files app unregistered the default file handler for .zip because Caret registered for a wider MIME type.
