### ISSUE TITLE
Caret Freezing

### ISSUE THREAD

**Issue by langsor** [thomaswilburn/Caret#723] opened 2020-03-23 02:47 UTC
### Type of issue (choose one):
  - [X] Bug

### Test steps

Recently, when I type into Caret it simply freezes. 

This started happening within the last couple days.

This happens repeatedly every time I open and try to use it. I reset it's prefs. I reinstalled it. I shut down all other apps. No go.

I can not save work, I can not shut it down. I have to "close" it from the launch bar.

### Description

To not freeze.

### System details

ChromeOS, latest version, developer mode.

Asus Chromebook

![image](https://user-images.githubusercontent.com/5402040/77275500-af862900-6c75-11ea-822b-aeab5b6facd7.png)

**Comment by leesajay** [comment] 2020-04-01 00:51
I have also experienced this, three times in the last week or so. I have not (yet) reset or uninstalled. Quitting and reopening allows me to continue using the app. I am on the latest Chrome OS not in developer mode. I will turn on error collection mode and report back.

**Comment by MaseratiPilot** [comment] 2020-04-02 01:01
I am also having this same problem.
I have to close the app.

One time I waited 20 minutes or so (didn't time it exactly) and it came back.  Within a few minutes it happened again.

Any ideas?

**Comment by thomaswilburn** [comment] 2020-04-02 01:14
On this end, nothing has substantially changed in Caret's code for at least a year. I don't know why this is happening. But given Google's plan to deprecate these apps very soon, I don't have a lot of time to try debugging it. I will happily take a pull request if someone provides a fix, however.

**Comment by langsor** [comment] 2020-04-02 15:29
Bummer. Yet, I understand.
I rely heavily on Caret for development and everything else on my Chromebook.
I've never bought any upgrade package because the free version has everything I need. But such a good app deserves to stay alive.
When you say Google is deprecating these apps, is that the decision they made in 2018? Could Caret be ported as a Progressive Web App and still be as robust as it is now? Most PWAs are pretty clunky still.
My guess is that some ChromeOS update broke Caret. Sadly this is out of my ability to troubleshoot.
The article I read says that Google intends to keep apps alive for Chromebooks. Not sure what caveats that comes with.
Let me know if there's anything I can do to support making Caret work again. 
Not sure how to access the source code / internals of Caret. 
I'm still having this problem and having to look for alternatives--there isn't anything else good out there.

Either way, thank you for making such a good app available. It's been really good.

Cheers,
Kevin

**Comment by leohomer** [comment] 2020-04-15 04:35
I want to let you know this happened to me as well.  I had to kill the window each time.  I tried restarting the background page, but that didn't help.  I happened upon a version of cloud 9 that also uses the ace editor that run with local storage.  I tried using it for a while and then the window it was in locked up the same way.  I couldn't move it, use any keys, even the mouse wasn't working.  I wondering if this a chrome problem with ace and not caret.

**Comment by leesajay** [comment] 2020-04-15 17:00
This may or may not be a helpful update but I have not had any more problems since the latest Chrome OS update (last week?).

**Comment by leohomer** [comment] 2020-04-15 18:11
Sorry. No dice.  I got the update too.  I also tried a third program that
uses ace on chrome.  It was an older program in the web store, that is no
longer supported and hadn't been update since 2018.  I thought maybe it was
using an older version of ace and that would make the difference.  Nope,
that one locked almost as soon as I started using it.  This may be a
complication of ace under chrome.  So your program, the other editor code
pad at
https://chrome.google.com/webstore/detail/code-pad-text-editor/adaepfiocmagdimjecpifghcgfjlfmkh
and
a cloud 9 online using local storage, but using ace at
https://c9.github.io/core/ just to try it.  All three locked up.  Yesterday
I file I had just finished coding and was looking at in Caret when it
locked got zeroed out and I lost all the changes.  Luckily I had backed up
the original, but I can't take that chance anymore.

Thanks,
Mark

**Comment by eritain** [comment] 2020-04-27 23:50
I have a similar freezing bug that appeared about the same time. Also happens in texteditor.co so the problem is not Caret itself but something they both use. 

I've found I can unfreeze them by minimizing the window and bringing it back.

**Comment by thomaswilburn** [comment] 2020-04-28 01:30
Given that this seems to be a problem with Ace, and not with Caret at all, I'm going to close this issue.

**Closed by thomaswilburn** 2020-04-28 01:30 UTC
