### ISSUE TITLE
[request] unsaved files exist forever

### ISSUE THREAD

**Issue by fghhfg** [thomaswilburn/Caret#431] opened 2015-09-01 03:16 UTC
as Notepad++

Unsaved files exist forever if you don't close that tab.

It will exist even after app has crashed.

It really useful for some scratch.

**Comment by thomaswilburn** [comment] 2015-09-01 03:26
Duplicate of another issue.

**Closed by thomaswilburn** 2015-09-01 03:26 UTC

**Comment by fghhfg** [comment] 2015-09-01 03:37
#94 #161 #178 #192
